### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by denzo** [Vestorly/ember-cli-preloader#11] opened 2016-11-24 04:29 UTC
![screen shot 2016-11-24 at 3 28 58 pm](https://cloud.githubusercontent.com/assets/1874772/20586712/cc18be6c-b25a-11e6-821c-2f7977a0d49d.png)

**Comment by joebartels** [comment] 2016-11-28 16:45
believe this to be duplicate of https://github.com/Vestorly/ember-cli-preloader/pull/9

There was a PR to fix this - I halted on merging because it required a rebase (tests were failing). After seeing you opening issue on same deprecation I decided to take the plunge and merge, despite tests failing. 

Assuming master has no failing tests, I'll submit a new version to npm

**Closed** 2016-11-28 16:45 UTC
